application: olda-blog
version: dev
runtime: python27
api_version: 1
threadsafe: yes

error_handlers:
- file: default_error.html

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /estatico
  static_dir: estatico

- url: .*
  script: blog.app
  secure: always



libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"